# Gems
gems: [jekyll-paginate]

# Permalinks

# Setup
title:               s-v-t
tagline:             'i am a robot'
description:         'Projects and stuff by <a href="https://twitter.com/achimkoh" target="_blank">@achimkoh</a>.'
url:                 https://scalarvectortensor.net # the base hostname & protocol for your site
baseurl:             '' # the subpath of your site, e.g. /blog
paginate:            5
permalink:           pretty
twitter_username: achimkoh
github_username:  achimkoh

# About/contact
author:
  name:              Achim Koh
  url:               https://twitter.com/achimkoh
  email:             achim.koh@gmail.com

# Custom vars
version:             1.0.0

# Build settings
# markdown: kramdown
# include: ['_pages']